### ISSUE TITLE
Are GCM / CCM better?

### ISSUE THREAD

**Issue by ishepherd** [rzubek/easy-cryptography#2]
This project uses AES with a CBC-then-HMAC approach.

.NET Core gained the [AesGcm](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm?view=net-7.0) and AesCcm classes, implementing GCM and CCM crypto modes.

I've seen claims that GCM/CCM, which are designed for "authenticated encryption", are preferable to CBC-then-HMAC. But I don't have the crypto background to evaluate these claims.

If you were starting this project today, and if you didn't need .NET Standard support, would you prefer GCM/CCM?
And why?
And which?

**Comment by rzubek** [comment]
Thank you! Yeah, CBC can be problematic, because while it's a block cipher, interactions between blocks are insufficient, in a way that could potentially allow for undetectable data tampering - which is why HMAC gets added to detect tampering, but then the onus is on the author to add the hash and recipient to actually check the hash. "Authenticated" schemes are safer for common cases, because checking validity is baked right in.

It's too bad that old versions of .NET only used CBC. But it might be worth it to break backward compatibility, and switch over to better counter modes.

**Comment by ishepherd** [comment]
Thanks @rzubek! Cool. that is essentially what I heard, thanks for reinforcing it.

This repo is a great demo and taught me a bit. Thanks again 🚀

**Comment by ishepherd** [comment]
How to decide between GCM and CCM?

**Comment by rzubek** [comment]
Hey, thanks!

As for mode choice, I believe GCM parallelizes better, so should allow for faster implementations. But in terms of authentication they should both be good choices.
